name: mcp-solr-search

# Channels to search for packages
channels:
  - defaults
  - conda-forge

# List of dependencies
dependencies:
  - python=3.12
  - numpy
  - requests>=2.28.2
  - pytest>=7.0.0
  - black
  - httpx>=0.24.0
  - uvicorn>=0.24.0
  - fastapi>=0.104.0
  - aiohttp>=3.8.5
  - python-dotenv>=1.0.0
  - pydantic>=2.0.0
  - pip
  - pip:
    - mcp-server
